### ISSUE TITLE
Separate out datamodel for primsa and graphql schema.

### ISSUE THREAD

**Issue by 5achinJani** [redbluenat/graphql-server#1]
![image](https://user-images.githubusercontent.com/23077544/54811629-27122880-4caf-11e9-8665-37e8191be742.png)
AuthPayload doesn't belong in the datamodels. It should be in schema.graphql cause we're not creating a table for AuthPayload. We're defining it for the end user who uses graphql endpoint.

![image](https://user-images.githubusercontent.com/23077544/54811829-9ee05300-4caf-11e9-84e2-1896fe02366e.png)
Firstly you haven't imported the `User` definition here  and it the User definition would expose the `password` field to the end user whoever is querying it. Hence there should be separate definition for User schema for both the prisma datamodels and schema.graphql.

**Comment by redbluenat** [comment]
Hi, thanks for your comment. I agree with you about improvement concept but it is just a sample project. I wrote this code just to show how to integrate everything together with some simple models as an example :) ofc here is a lot of things which can be improve for commercial use.
